# Generated by Django 5.2.7 on 2025-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.CharField(max_length=3)),
                ('base_ccy', models.CharField(max_length=3)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source', models.CharField(choices=[('cards', 'Non-cash (cards)'), ('cash', 'Cash')], default='cards', max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at', 'ccy'],
            },
        ),
    ]
